--
-- Tabela: categories
--
CREATE TABLE public.categories (
                                   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   description character varying(255),
                                   name character varying(255) NOT NULL,
                                   CONSTRAINT categories_pkey PRIMARY KEY (id),
                                   CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

--
-- Tabela: movies
--
CREATE TABLE public.movies (
                               id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               background_path character varying(500),
                               description character varying(1000),
                               logo_path character varying(255),
                               release_date integer,
                               thumbnail_path character varying(255),
                               title character varying(255) NOT NULL,
                               video_file_path character varying(255),
                               category_id bigint NOT NULL,
                               tmdb_id bigint,
                               shinden_series_url character varying(255),
                               tags character varying(500),
                               CONSTRAINT movies_pkey PRIMARY KEY (id),
                               CONSTRAINT fkn00vsw85tow1xyebya4hih3ke FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

--
-- Tabela: episodes
--
CREATE TABLE public.episodes (
                                 id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 ep_description text,
                                 episode_number integer,
                                 title character varying(255),
                                 video_file_path text,
                                 movie_id bigint,
                                 source_embed_url text,
                                 shinden_url character varying(255),
                                 CONSTRAINT episodes_pkey PRIMARY KEY (id),
                                 CONSTRAINT fkr0m8qnjio0s9c6s53p68nxpg FOREIGN KEY (movie_id) REFERENCES public.movies(id)
);

--
-- Tabela: users
--
CREATE TABLE public.users (
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              email character varying(255) NOT NULL,
                              password character varying(255) NOT NULL,
                              role character varying(255),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Tabela: profiles
--
CREATE TABLE public.profiles (
                                 id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 avatar_url character varying(255),
                                 profile_name character varying(255),
                                 user_id bigint,
                                 CONSTRAINT profiles_pkey PRIMARY KEY (id),
                                 CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id)
);

--
-- Tabela: watchlists
--
CREATE TABLE public.watchlists (
                                   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   added_at timestamp(6) without time zone,
                                   movie_id bigint NOT NULL,
                                   profile_id bigint NOT NULL,
                                   CONSTRAINT watchlists_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk2o4qyxqkybphjrjo843lg65r4 FOREIGN KEY (movie_id) REFERENCES public.movies(id),
                                   CONSTRAINT fkk8392d5u7i0q216xoporwl5yc FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);