CREATE TABLE IF NOT EXISTS public.playback_progress (
                                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                        profile_id BIGINT NOT NULL,
                                                        movie_id BIGINT NOT NULL,

                                                        timestamp_seconds INTEGER NOT NULL,
                                                        is_completed BOOLEAN NOT NULL DEFAULT FALSE,

                                                        updated_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT fk_playback_progress_profile
    FOREIGN KEY (profile_id)
    REFERENCES public.profiles(id)
                                                                                ON DELETE CASCADE,

    CONSTRAINT fk_playback_progress_movie
    FOREIGN KEY (episode_id)
    REFERENCES public.episodes(id)
                                                                                ON DELETE CASCADE,

    CONSTRAINT uk_playback_progress_profile_episode
    UNIQUE (profile_id, episode_id)
    );

CREATE INDEX IF NOT EXISTS idx_playback_progress_profile_id
    ON public.playback_progress(profile_id);

CREATE INDEX IF NOT EXISTS idx_playback_progress_episode_id
    ON public.playback_progress(episode_id);