-- Tabele i sekwencje

CREATE TABLE public.categories (
                                   id bigint NOT NULL,
                                   description character varying(255),
                                   name character varying(255) NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.episodes (
                                 id bigint NOT NULL,
                                 episode_number integer,
                                 title character varying(255),
                                 video_file_path character varying(255),
                                 movie_id bigint,
                                 ep_description character varying(255)
);

ALTER TABLE public.episodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.episodes_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.movies (
                               id bigint NOT NULL,
                               description character varying(1000),
                               release_date integer,
                               thumbnail_url character varying(255),
                               title character varying(255) NOT NULL,
                               video_file_path character varying(255),
                               category_id bigint NOT NULL,
                               thumbnail_path character varying(255),
                               background_path character varying(500),
                               logo_path character varying(255)
);

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.profiles (
                                 id bigint NOT NULL,
                                 avatar_url character varying(255),
                                 profile_name character varying(255),
                                 user_id bigint
);

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email character varying(255) NOT NULL,
                              password character varying(255) NOT NULL,
                              role character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.watchlists (
                                   id bigint NOT NULL,
                                   added_at timestamp(6) without time zone,
                                   movie_id bigint NOT NULL,
                                   profile_id bigint NOT NULL
);

ALTER TABLE public.watchlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlists_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Klucze główne (Primary Keys)

ALTER TABLE ONLY public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.episodes ADD CONSTRAINT episodes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.movies ADD CONSTRAINT movies_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.watchlists ADD CONSTRAINT watchlists_pkey PRIMARY KEY (id);

-- Unikalne wartości (Unique Constraints)

ALTER TABLE ONLY public.users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.categories ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

-- Klucze obce (Foreign Keys)

ALTER TABLE ONLY public.watchlists
    ADD CONSTRAINT fk2o4qyxqkybphjrjo843lg65r4 FOREIGN KEY (movie_id) REFERENCES public.movies(id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.watchlists
    ADD CONSTRAINT fkk8392d5u7i0q216xoporwl5yc FOREIGN KEY (profile_id) REFERENCES public.profiles(id);

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT fkn00vsw85tow1xyebya4hih3ke FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.episodes
    ADD CONSTRAINT fkr0m8qnjio0s9c6s53p68nxpg FOREIGN KEY (movie_id) REFERENCES public.movies(id);